import { ethers } from "ethers";

// categories from udemy categories
export const categoriesTree = [
  {
    label: "Business",
    items: [
      { label: "Business Strategy" },
      { label: "Business Law" },
      { label: "Business Communication" },
      { label: "Project Management" },
      { label: "Leadership" },
      { label: "Entrepreneurship" },
      { label: "Sales" },
      { label: "Operations" },
      { label: "Home Business" },
      { label: "Human Resources" },
      { label: "Management" },
      { label: "IT & Software" },
      { label: "Office Productivity" },
      { label: "Personal Development" },
    ],
  },
  {
    label: "Finance & Accounting",
    items: [
      { label: "Finance" },
      { label: "Accounting" },
      { label: "Investing" },
      { label: "Trading" },
      { label: "Cryptocurrency" },
      { label: "Stocks" },
      { label: "Real Estate" },
      { label: "Personal Finance" },
      { label: "Tax Preparation" },
      { label: "Other Finance" },
    ],
  },
  {
    label: "Computers",
    items: [
      {
        label: "Software",
        items: [
          { label: "Desktop Software" },
          { label: "Mobile Software" },
          { label: "Web Software" },
          { label: "Operating Systems" },
          { label: "Database Software" },
          { label: "Developer Tools" },
          { label: "Utilities" },
          { label: "Other Software" },
        ],
      },
      {
        label: "Development",
        items: [
          { label: "Web Development" },
          { label: "Data science" },
          { label: "Mobile Development" },
          { label: "Game Development" },
          { label: "Programming Languages" },
          { label: "Databases" },
          { label: "Software Testing" },
          { label: "Software Engineering" },
          { label: "Development Tools" },
          { label: "E-Commerce" },
          { label: "No Code Development" },
          { label: "Web Design" },
          { label: "User Experience" },
          { label: "Game Design" },
          { label: "Design Tools" },
          { label: "Business Analysis" },
        ],
      },
      { label: "Plugins", items: [{ label: "Plugin" }, { label: "Extension" }, { label: "Other Plugins" }] },
      { label: "Wallpapers" },
      { label: "Emojis" },
      { label: "Fonts" },
      {
        label: "IT & Software",
        items: [
          { label: "IT Certification" },
          { label: "Network & Security" },
          { label: "Hardware" },
          { label: "Operating Systems" },
          { label: "Other IT & Software" },
        ],
      },
    ],
  },
  {
    label: "Marketing",
    items: [
      { label: "Digital Marketing" },
      { label: "Influencer Marketing" },

      { label: "Search Engine Optimization" },
      { label: "Social Media Marketing" },
      { label: "Marketing Fundamentals" },
      { label: "Email Marketing" },
      { label: "Affiliate Marketing" },
      { label: "Advertising" },
      { label: "Branding" },
      { label: "Public Relations" },
      { label: "Marketing Strategy" },
      { label: "Growth Hacking" },
      { label: "Product Marketing" },
      { label: "Content Marketing" },
      { label: "Video & Mobile Marketing" },
      { label: "Analytics & Automation" },
      { label: "Other Marketing" },
    ],
  },
  {
    label: "Productivity",
    items: [
      { label: "Capital Productivity" },
      { label: "Material Productivity" },
      { label: "Labor Productivity" },
      { label: "Total Factor Productivity" },
      {
        label: "Office Productivity",
        items: [
          { label: "Microsoft" },
          { label: "Google" },
          { label: "Apple" },
          { label: "Oracle" },
          { label: "Adobe" },
          { label: "Autodesk" },
          { label: "SAS" },
          { label: "Sage" },
          { label: "SAP" },
          { label: "Other Office Productivity" },
        ],
      },
      {
        label: "Personal Productivity",
        items: [
          { label: "Time Management" },
          { label: "Personal Transformation" },
          { label: "Stress Management" },
          { label: "Memory & Study Skills" },
          { label: "Other Personal Productivity" },
        ],
      },
      { label: "Productivity Tools" },
    ],
  },
  {
    label: "Personal Development",
    items: [
      { label: "Personal Transformation" },
      { label: "Happiness" },
      { label: "Productivity" },
      { label: "Personal Finance" },
      { label: "Parenting & Relationships" },
      { label: "Motivation" },
      { label: "Memory & Study Skills" },
      { label: "Leadership" },
      { label: "Creativity" },
      { label: "Career Development" },
      { label: "Communication" },
      { label: "Self Esteem" },
      { label: "Stress Management" },
      { label: "Time Management" },
      { label: "Other Personal Development" },
    ],
  },
  {
    label: "Lifestyle",
    items: [
      { label: "Fashion" },
      { label: "Photography" },
      { label: "Arts & Crafts" },
      { label: "Beauty & Makeup" },

      { label: "Food & Beverage" },
      { label: "Travel" },
      { label: "Home Improvement" },
      { label: "Pet Care & Training" },
      { label: "Gaming" },
      { label: "Tracker" },
      { label: "Wellness" },
      { label: "Fine Art" },
      { label: "Other Lifestyle" },
    ],
  },
  {
    label: "Health & Fitness",
    items: [
      { label: "Fitness" },
      { label: "Nutrition" },
      { label: "Mental Health" },
      { label: "Dieting" },
      { label: "Safety & First Aid" },
      { label: "Yoga" },
      { label: "Self Defense" },
      { label: "Martial Arts" },
      { label: "Weight Loss" },
      { label: "Gymnastics" },
      { label: "Pregnancy & Fertility" },
      { label: "Meditation" },
      { label: "Sports" },
      { label: "Dance" },
      { label: "Pilates" },
      { label: "Aerobics" },
      { label: "Zumba" },
      { label: "Tai Chi" },
      { label: "Other Health & Fitness" },
    ],
  },

  {
    label: "Media",
    items: [
      {
        label: "Audio",
        items: [
          { label: "Engineering" },
          {
            label: "Sound Effects",
            items: [
              { label: "Nature" },
              { label: "Animals" },
              { label: "Human" },
              { label: "Mechanical" },
              { label: "Transportation" },
              { label: "Weapons" },

              { label: "Other Sound Effects" },
            ],
          },
          { label: "Tools" },
          { label: "Mixing" },
          { label: "Mastering" },
          { label: "Production" },
          { label: "Other Audio" },
        ],
      },
      {
        label: "Animation",
        items: [
          { label: "Fundamentals" },
          { label: "Tools" },
          { label: "Techniques" },
          { label: "Production" },
          { label: "Editing" },
          { label: "Business" },
          { label: "Other Animation" },
        ],
      },
      {
        label: "Video",
        items: [
          { label: "Fundamentals" },
          { label: "Tools" },
          { label: "Techniques" },
          { label: "Production" },
          { label: "Editing" },
          { label: "Business" },
          { label: "Other Video" },
        ],
      },
      {
        label: "Photography",
        items: [
          { label: "Fundamentals" },
          { label: "Digital Photography" },
          { label: "Tools" },
          { label: "Commercial Photography" },
          { label: "Business" },
          { label: "Composition" },
          { label: "Lighting" },
          { label: "Techniques" },
          { label: "Equipment" },
          { label: "Other Photography" },
        ],
      },
      {
        label: "Music",
        items: [
          { label: "Fundamentals" },
          { label: "Techniques" },
          { label: "Music Theory" },
          {
            label: "Instruments",
            items: [
              { label: "Guitar" },
              { label: "Piano" },
              { label: "Drums" },
              { label: "Ukulele" },
              { label: "Bass" },
              { label: "Violin" },
              { label: "Saxophone" },
              { label: "Trumpet" },
              { label: "Flute" },
              { label: "Trombone" },
              { label: "Voice" },
              { label: "Other Instruments" },
            ],
          },
          { label: "Production" },
          { label: "Performance" },
          { label: "Business" },
          {
            label: "Music Software",
            items: [
              { label: "Cubase" },
              { label: "FL Studio" },
              { label: "Logic Pro" },
              { label: "Ableton Live" },
              { label: "Pro Tools" },
              { label: "Reason" },
              { label: "Studio One" },
              { label: "Reaper" },
              { label: "GarageBand" },
              { label: "Sonar" },
              { label: "Bitwig" },
              { label: "Tracktion" },
              { label: "Mixcraft" },
              { label: "Cakewalk" },
              { label: "Audacity" },
              { label: "LMMS" },
              { label: "Waveform" },
              { label: "Samplitude" },
              { label: "Studio 3T" },
              { label: "Sibelius" },
              { label: "Finale" },
              { label: "Notion" },
              { label: "MuseScore" },
              { label: "Coda" },
              { label: "ScoreCloud" },
              { label: "Noteflight" },
              { label: "Flat" },
              { label: "MusicXML" },
              { label: "DAW" },
              { label: "VST" },
              { label: "Audio Plugins" },
              { label: "Other Music Software" },
            ],
          },
          { label: "Songs" },
          { label: "Other Music" },
        ],
      },
      {
        label: "Graphics",
        items: [
          { label: "Posters" },
          { label: "Logos" },
          { label: "Business Cards" },
          { label: "Banners" },
          { label: "Flyers" },
          { label: "Brochures" },
          { label: "Book Covers" },
          { label: "Social Media Graphics" },
          { label: "Web Graphics" },
          { label: "Print Graphics" },
          { label: "Presentation Graphics" },
          { label: "Typography" },
          { label: "Illustrations" },
          { label: "Drawing" },
          { label: "Sketching" },
          { label: "Painting" },
          {
            label: "Graphics Software",
            items: [
              { label: "CorelDRAW" },
              { label: "Gimp" },
              { label: "Canva" },
              { label: "Affinity Designer" },
              { label: "Affinity Photo" },
              { label: "Figma" },
              { label: "Adobe XD" },
              { label: "Adobe Illustrator" },
              { label: "Adobe Photoshop" },
              { label: "Adobe InDesign" },
              { label: "Adobe Spark" },
              { label: "Adobe Lightroom" },
              { label: "Adobe Premiere Pro" },
              { label: "Adobe After Effects" },
              { label: "Adobe Audition" },
              { label: "Adobe Animate" },
              { label: "Adobe Character Animator" },
              { label: "Adobe Fresco" },
              { label: "Adobe Dimension" },
            ],
          },
          { label: "Other Graphics" },
        ],
      },
      {
        label: "3D",
        items: [
          { label: "3D Model" },
          { label: "3D Animation" },
          { label: "3D Print File" },
          { label: "3D Design" },
          { label: "3D Print Assembly File" },
          { label: "3D Techniques" },
          { label: "3D Production" },
          { label: "3D Editing" },
          {
            label: "3D Software",
            items: [
              { label: "Blender" },
              { label: "Cinema 4D" },
              { label: "3ds Max" },
              { label: "Maya" },
              { label: "ZBrush" },
              { label: "MODO" },
              { label: "KeyShot" },
              { label: "Rhino" },
              { label: "Lightwave" },
              { label: "SolidWorks" },
              { label: "Fusion 360" },
              { label: "AutoCAD" },
              { label: "SketchUp" },
              { label: "Revit" },
              { label: "Inventor" },
              { label: "AutoCAD LT" },
              { label: "AutoCAD Architecture" },
              { label: "AutoCAD Civil 3D" },
              { label: "AutoCAD Electrical" },
              { label: "AutoCAD Map 3D" },
              { label: "AutoCAD Mechanical" },
              { label: "AutoCAD MEP" },
              { label: "AutoCAD Plant 3D" },
              { label: "AutoCAD Raster Design" },
              { label: "AutoCAD Structural Detailing" },
              { label: "AutoCAD Utility Design" },
              { label: "AutoCAD Web App" },
            ],
          },
          { label: "Other 3D" },
        ],
      },
      { label: "Filters" },
    ],
  },

  {
    label: "Academics",
    items: [
      { label: "Academic Research" },
      { label: "Academic Writing" },
      { label: "Academic Papers" },
      { label: "Academic Essays" },
      { label: "Academic Editing" },
      { label: "Academic Proofreading" },
      { label: "Academic Translation" },
      { label: "Academic Consulting" },
      {
        label: "Academic Levels",
        items: [
          { label: "Elementary School" },
          { label: "Middle School" },
          { label: "High School" },
          { label: "College" },
          { label: "Graduate School" },
          { label: "Professional Development" },
          { label: "Test Prep" },
          { label: "Other Academic Levels" },
        ],
      },
      { label: "Academic Resources" },
    ],
  },

  {
    label: "Teaching",
    items: [
      {
        label: "Languages",
        items: [
          { label: "English" },
          { label: "Spanish" },
          { label: "French" },
          { label: "German" },
          { label: "Chinese" },
          { label: "Italian" },
          { label: "Japanese" },
          { label: "Russian" },
          { label: "Arabic" },
          { label: "Portuguese" },
          { label: "Korean" },
          { label: "Hindi" },
          { label: "Turkish" },
          { label: "Dutch" },
          { label: "Polish" },
          { label: "Swedish" },
          { label: "Norwegian" },
          { label: "Danish" },
          { label: "Czech" },
          { label: "Greek" },
          { label: "Hungarian" },
          { label: "Romanian" },
          { label: "Finnish" },
          { label: "Indonesian" },
          { label: "Hebrew" },
          { label: "Afrikaans" },
          { label: "Bengali" },
          { label: "Croatian" },
          { label: "Estonian" },
          { label: "Filipino" },
          { label: "Icelandic" },
          { label: "Latvian" },
          { label: "Lithuanian" },
          { label: "Serbian" },
          { label: "Slovak" },
          { label: "Slovenian" },
          { label: "Ukrainian" },
          { label: "Vietnamese" },
          { label: "Albanian" },
          { label: "Armenian" },
          { label: "Azerbaijani" },
          { label: "Basque" },
          { label: "Belarusian" },
          { label: "Bosnian" },
          { label: "Bulgarian" },
          { label: "Catalan" },
          { label: "Welsh" },
          { label: "Galician" },
          { label: "Georgian" },
          { label: "Gujarati" },
          { label: "Haitian Creole" },
          { label: "Hausa" },
          { label: "Igbo" },
          { label: "Javanese" },
          { label: "Kannada" },
          { label: "Khmer" },
          { label: "Lao" },
          { label: "Latin" },
          { label: "Macedonian" },
          { label: "Malay" },
          { label: "Malayalam" },
          { label: "Maltese" },
          { label: "Marathi" },
          { label: "Mongolian" },
          { label: "Nepali" },
          { label: "Persian" },
          { label: "Punjabi" },
          { label: "Somali" },
          { label: "Swahili" },
          { label: "Tamil" },
          { label: "Telugu" },
          { label: "Thai" },
          { label: "Yoruba" },
          { label: "Zulu" },
        ],
      },
      { label: "Teaching Fundamentals" },
      { label: "Teaching Tools" },
      { label: "Teaching Techniques" },
      { label: "Math" },
      { label: "Physics" },
      { label: "Science" },
      { label: "History" },
      { label: "Geography" },
      { label: "Politics" },
      { label: "Economics" },
      { label: "Psychology" },
      { label: "Philosophy" },
      { label: "Religion" },
      { label: "Sociology" },
      { label: "Anthropology" },
      { label: "Biology" },
      { label: "Chemistry" },
      { label: "Engineering" },
      { label: "Computer Science" },
      { label: "Art" },
      { label: "Music" },
      { label: "Dance" },
      { label: "Theater" },
      { label: "Film" },
      { label: "Design" },
      { label: "Architecture" },
      { label: "Photography" },
      { label: "Fashion" },
      { label: "Cooking" },
      { label: "Nutrition" },
      { label: "Health" },
      { label: "Fitness" },
      { label: "Sports" },
      { label: "Gaming" },
      { label: "Writing" },
      { label: "Reading" },
      { label: "Business" },
      { label: "Education" },
      { label: "Test Prep" },
      { label: "College" },
      { label: "K-12" },
      { label: "Higher Education" },
      { label: "Professional Development" },
      { label: "Online Education" },
      { label: "Teaching Resources" },
      { label: "Other Teaching" },
    ],
  },

  {
    label: "Books & Journals",
    items: [
      {
        label: "Fiction",
        items: [
          { label: "Fantasy" },
          { label: "Science Fiction" },
          { label: "Romance" },
          { label: "Mystery" },
          { label: "Thriller" },
          { label: "Horror" },
          { label: "Other Fiction" },
        ],
      },
      {
        label: "Nonfiction",
        items: [
          { label: "Biography" },
          { label: "Autobiography" },
          { label: "Memoir" },
          { label: "Self Help" },
          { label: "Biographies" },
          { label: "Business Books" },
          { label: "Cookbooks" },
          { label: "Recepie Book" },
          { label: "Children's Books" },
          { label: "Comics" },
          { label: "Graphic Novels" },
          { label: "Poetry" },
          { label: "Romance" },
          { label: "Self-Help" },
          { label: "Health" },
          { label: "History" },
          { label: "Travel" },
          { label: "Guide" },
          { label: "Religion" },
          { label: "Spirituality" },
          { label: "Family" },
          { label: "Humor" },
          { label: "Music" },
          { label: "Sports" },
          { label: "Art" },
          { label: "Photography" },
          { label: "Film" },
          { label: "Design" },
          { label: "Fashion" },
          { label: "Cooking" },
          { label: "Crafts" },
          { label: "Gardening" },
          { label: "Hobbies" },
          { label: "Home & Garden" },
          { label: "Pets" },
          { label: "Games" },
          { label: "Entertainment" },
          { label: "Reference" },
          { label: "Science" },
          { label: "Math" },
          { label: "Social Science" },
          { label: "Computers" },
          { label: "Technology" },
          { label: "Engineering" },
          { label: "Transportation" },
          { label: "Medicine" },
          { label: "Law" },
          { label: "Business & Money" },
          { label: "Economics" },
          { label: "Finance" },
          { label: "Marketing" },
          { label: "Personal Finance" },
          { label: "Investing" },
          { label: "Industries" },
          { label: "Management" },
          { label: "Strategy" },
          { label: "Human Resources" },
          { label: "Real Estate" },
          { label: "Small Business" },
          { label: "Entrepreneurship" },
          { label: "Personal Growth" },
          { label: "Motivational" },
          { label: "Success" },
          { label: "Inspirational" },
          { label: "Parenting" },
          { label: "Relationships" },
          { label: "Self-Improvement" },
          { label: "New Age" },
          { label: "Psychology" },
          { label: "Philosophy" },
          { label: "Politics" },
          { label: "Anthropology" },
          { label: "Archaeology" },
          { label: "Cultural" },
          { label: "Education" },
          { label: "Other" },
        ],
      },
      {
        label: "Journals",
        items: [{ label: "Newsletter" }, { label: "Blog" }, { label: "Podcast" }, { label: "Other Journals" }],
      },
      {
        label: "Printouts",
        items: [
          { label: "Printout" },
          { label: "Origami" },
          { label: "Paper Craft" },
          { label: "Coloring Book" },
          { label: "Coloring sheets" },
          { label: "Other Printouts" },
        ],
      },
      { label: "Short Fiction" },
      { label: "Short Non-Fiction" },
      { label: "Posters" },
      { label: "Other Books" },
      { label: "Other Journal" },
      { label: "Other" },
    ],
  },
  {
    label: "Courses & Guides & Tutorials",
    items: [
      {
        label: "Courses",
        items: [
          { label: "Course" },
          { label: "Class" },
          { label: "Workshop" },
          { label: "Audio" },
          { label: "Video" },
          { label: "Music" },
          { label: "Language" },
          { label: "Art" },
          { label: "Photography" },
          { label: "Cooking" },
          { label: "Crafting" },
          { label: "Gaming" },
          { label: "Business" },
          { label: "Marketing" },
          { label: "Finance" },
          { label: "Design" },
          { label: "Fashion" },
          { label: "Writing" },
          { label: "Drawing" },
          { label: "Painting" },
          { label: "Singing" },
          { label: "Dancing" },
          { label: "Gardening" },
          { label: "Home Improvement" },
          { label: "Pet Care" },
          { label: "IT" },
          { label: "Self-Improvement" },
          { label: "Health" },
          { label: "Workout" },
          { label: "Certification" },
          { label: "Other" },
        ],
      },
      {
        label: "Guide",
        items: [
          { label: "Drawing" },
          { label: "Writing" },
          { label: "Cooking" },
          { label: "Travel" },
          { label: "Home Improvement" },
          { label: "Pet Care" },
          { label: "Gaming" },
          { label: "Other" },
        ],
      },
      {
        label: "Tutorial",
        items: [
          { label: "Writing" },
          { label: "Development" },
          { label: "Programming" },
          { label: "Cooking" },
          { label: "Drawing" },
          { label: "Painting" },
          { label: "Singing" },
          { label: "How-tos" },
          { label: "Gaming" },
          { label: "Other" },
        ],
      },
    ],
  },

  {
    label: "Design",
    items: [
      { label: "Design Tools" },
      { label: "Design Strategy" },
      { label: "Design Thinking" },
      { label: "Interior Design" },
      { label: "User Experience" },
      { label: "Game Design" },
      { label: "Architecture" },
      { label: "Fashion" },
      { label: "Landscape" },
      {
        label: "Graphics",
        items: [
          { label: "Web Graphics" },
          { label: "Mobile Graphics" },
          { label: "Desktop Graphics" },
          { label: "3D" },
          { label: "Animation" },
          { label: "Illustration" },
          { label: "Other Graphics" },
        ],
      },
      { label: "Theme" },
      { label: "Template" },
      { label: "Plugin" },
      { label: "Extension" },
      { label: "Other Design" },
    ],
  },
  {
    label: "Games",
    items: [
      { label: "Video games" },
      { label: "Web games" },
      { label: "Mobile games" },
      { label: "Desktop games" },
      { label: "Console games" },
      { label: "Board games" },
      { label: "Card games" },
      { label: "Printable games" },
      { label: "Riddles" },
      { label: "Other Games" },
    ],
  },

  {
    label: "Stock",
    items: [
      { label: "Photos" },
      { label: "Videos" },
      { label: "Music" },
      { label: "Audio" },
      { label: "Illustrations" },
      { label: "Vectors" },
      { label: "Films" },
      {
        label: "Themes",
        items: [
          { label: "Theme" },
          { label: "Web theme" },
          { label: "Plugin" },
          { label: "Extension" },
          { label: "Other Themes" },
        ],
      },
      {
        label: "Templates",
        items: [
          { label: "Template" },
          { label: "Web Template" },
          { label: "Mobile Template" },
          { label: "Desktop Template" },
          { label: "Other Templates" },
        ],
      },
      {
        label: "Graphics",
        items: [
          { label: "Graphics" },
          { label: "Web Graphics" },
          { label: "Mobile Graphics" },
          { label: "Desktop Graphics" },
          { label: "3D Graphics" },
          { label: "Other Graphics" },
        ],
      },
      {
        label: "3D",
        items: [
          { label: "3D Models" },
          { label: "3D Objects" },
          { label: "3D Textures" },
          { label: "3D Scenes" },
          { label: "3D Materials" },
          { label: "3D Animations" },
          { label: "3D Characters" },
          { label: "3D Animals" },
          { label: "3D Environments" },
          { label: "3D Props" },
          { label: "3D Vehicles" },
          { label: "3D Weapons" },
          { label: "3D Buildings" },
          { label: "3D Furniture" },
          { label: "3D Plants" },
          { label: "3D Trees" },
        ],
      },
      { label: "Video Animation Intros" },
      { label: "Animation" },
      { label: "Titles" },
      {
        label: "Presets & Filters",
        items: [
          { label: "Presets", items: [{ label: "LUTs" }] },
          { label: "Filters", items: [{ label: "Audio Filters" }, { label: "Video Filters" }] },
        ],
      },
      { label: "Other Stock" },
    ],
  },
  {
    label: "Services",
    items: [
      { label: "Service" },
      { label: "Web Service" },
      { label: "Mobile Service" },
      { label: "Desktop Service" },
      { label: "Other Service" },
    ],
  },
];

export const categoryList = [
  { label: "General", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("General")).toString() },
  { label: "Text", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Text")).toString() },
  { label: "Image", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Image")).toString() },
  { label: "Data", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Data")).toString() },
  { label: "Map", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Map")).toString() },
  { label: "Audio", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Audio")).toString() },
  { label: "Video", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Video")).toString() },
  { label: "Model", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Model")).toString() },
  { label: "Other", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Other")).toString() },

  { label: "Book", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Book")).toString() },
  { label: "Fiction book", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Fiction book")).toString() },
  { label: "Non-fiction book", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Non-fiction book")).toString() },
  { label: "Short stories", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Short stories")).toString() },

  { label: "Membership", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Membership")).toString() },
  { label: "Planners", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Planners")).toString() },
  { label: "Guides", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Guides")).toString() },
  { label: "Drawing guides", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Drawing guides")).toString() },
  { label: "Travel guides", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Travel guides")).toString() },
  {
    label: "Self-publishing guides",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Self-publishing guides")).toString(),
  },
  { label: "Printout origami", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Printout origami")).toString() },
  {
    label: "Printable coloring sheets",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Printable coloring sheets")).toString(),
  },

  { label: "Newsletter", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Newsletter")).toString() },

  {
    label: "E-learning course",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("E-learning course")).toString(),
  },
  { label: "Community", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Community")).toString() },
  { label: "Courses", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Courses")).toString() },
  {
    label: "Certified courses",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Certified courses")).toString(),
  },
  { label: "Audio course", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Audio course")).toString() },
  { label: "Video course", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Video course")).toString() },

  { label: "Journals", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Journal")).toString() },
  {
    label: "Printable journals",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Printable journal")).toString(),
  },

  { label: "Tracker", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Tracker")).toString() },
  { label: "Wellness tracker", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Wellness tracker")).toString() },

  { label: "Wallpapers", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Wallpapers")).toString() },
  { label: "Emojis", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Emojis")).toString() },
  { label: "Posters", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Posters")).toString() },
  { label: "Fonts", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Fonts")).toString() },
  { label: "Templates", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Templates")).toString() },
  {
    label: "3D printer design files",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("3D printer design files")).toString(),
  },
  { label: "3D design files", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("3D design files")).toString() },
  { label: "3D files", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("3D files")).toString() },
  { label: "Sets", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Sets")).toString() },
  { label: "Icon sets", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Icon sets")).toString() },
  { label: "Animations", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Animations")).toString() },
  { label: "Video animations", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Video animations")).toString() },
  { label: "3D animations", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("3D animations")).toString() },
  {
    label: "Cartoon animations",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Cartoon animations")).toString(),
  },

  { label: "Designs", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Designs")).toString() },
  {
    label: "Architectural designs",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Architectural designs")).toString(),
  },
  { label: "Graphic designs", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Graphic designs")).toString() },
  { label: "Premade designs", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Premade designs")).toString() },

  { label: "Games", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("games")).toString() },
  { label: "Video games", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Video games")).toString() },
  { label: "Mobile games", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Mobile games")).toString() },
  { label: "Desktop games", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Desktop games")).toString() },
  { label: "Console games", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Console games")).toString() },
  { label: "Board games", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Board games")).toString() },
  { label: "Card games", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Card games")).toString() },
  {
    label: "Printable games and riddles",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Printable games and riddles")).toString(),
  },

  { label: "Themes", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Themes")).toString() },
  { label: "Website themes", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Website themes")).toString() },
  { label: "Music themes", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Music themes")).toString() },
  { label: "Video themes", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Video themes")).toString() },
  { label: "Slide themes", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Slide themes")).toString() },
  {
    label: "Spreadsheet themes",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Spreadsheet themes")).toString(),
  },

  { label: "Software", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Software")).toString() },
  { label: "Desktop software", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Desktop software")).toString() },
  { label: "Mobile software", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Mobile software")).toString() },
  { label: "Web software", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Web software")).toString() },
  { label: "Apps", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Apps")).toString() },
  { label: "Web apps", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Web apps")).toString() },
  { label: "Mobile apps", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Mobile apps")).toString() },
  { label: "Desktop apps", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Desktop apps")).toString() },

  { label: "Plugins", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Plugins")).toString() },
  { label: "Browser plugins", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Browser plugins")).toString() },
  { label: "Audio plugins", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Audio plugins")).toString() },
  { label: "Video plugins", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Video plugins")).toString() },

  { label: "Hosting", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Hosting")).toString() },
  { label: "Code snippets", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Code snippets")).toString() },
  { label: "Integrations", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Integrations")).toString() },
  { label: "Podcast", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Podcast")).toString() },
  { label: "Careers advice", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Careers advice")).toString() },
  { label: "Masterclasses", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Masterclasses")).toString() },
  { label: "Resources", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Resources")).toString() },

  { label: "Deleted chapters", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Deleted chapters")).toString() },
  { label: "Spin-offs", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Spin-offs")).toString() },

  { label: "Extra scenes", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Extra scenes")).toString() },

  {
    label: "Novel planning sheet",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Novel planning sheet")).toString(),
  },
  { label: "Tutorials", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Tutorials")).toString() },
  {
    label: "Painting video tutorials",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Painting video tutorials")).toString(),
  },
  {
    label: "Videography tutorials",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Videography tutorials")).toString(),
  },
  { label: "Music tutorials", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Music tutorials")).toString() },

  { label: "Designs", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Designs")).toString() },
  {
    label: "Clip art pictures",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Clip art pictures")).toString(),
  },
  { label: "Clip art symbols", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Clip art symbols")).toString() },

  { label: "Cooking", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Cooking")).toString() },
  { label: "Recipe books", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Recipe books")).toString() },
  { label: "Nutrition", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Nutrition")).toString() },
  { label: "Nutrition plans", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Nutrition plans")).toString() },
  { label: "Meal-prep plans", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Meal-prep plans")).toString() },

  { label: "Health", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Health")).toString() },
  { label: "Healthy living", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Healthy living")).toString() },
  {
    label: "Home recipes for healthy skin",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Home recipes for healthy skin")).toString(),
  },
  {
    label: "Hair and makeup tutorials",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Hair and makeup tutorials")).toString(),
  },

  { label: "Audiobook", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Audiobook")).toString() },
  { label: "Kids’ audiobook", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Kids’ audiobook")).toString() },
  {
    label: "Activities",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Activities")).toString(),
  },
  { label: "Trips", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Trips")).toString() },
  {
    label: "Field trips and activities",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Field trips and activities")).toString(),
  },
  {
    label: "Virtual field trips and activities",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Virtual field trips and activities")).toString(),
  },

  { label: "Songs", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Songs")).toString() },
  { label: "Album", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Album")).toString() },
  {
    label: "Downloadable songs",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Downloadable songs")).toString(),
  },
  { label: "Playlist", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Playlist")).toString() },
  { label: "Sound effects", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Sound effects")).toString() },
  { label: "Voiceovers", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Voiceovers")).toString() },
  {
    label: "Instrumental tracks",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Instrumental tracks")).toString(),
  },
  { label: "Beats", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Beats")).toString() },
  { label: "Workout plans", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Workout plans")).toString() },
  {
    label: "Workout video",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Workout video")).toString(),
  },

  { label: "Presets", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Presets")).toString() },
  {
    label: "Presets and filters",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Presets and filters")).toString(),
  },
  { label: "LUTs and presets", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("LUTs and presets")).toString() },
  { label: "Filters", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Filters")).toString() },
  { label: "Audio Filters", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Audio Filters")).toString() },
  { label: "Video Filters", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Video Filters")).toString() },
  { label: "Stock photos", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Stock photo")).toString() },
  { label: "Stock video", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Stock video")).toString() },
  { label: "Short films", value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Short films")).toString() },
  {
    label: "Video animation intros",
    value: ethers.utils.keccak256(ethers.utils.toUtf8Bytes("Video animation intros")),
  },
];
